---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: false
    checks:
      TODO:
        enabled: false
ratings:
  paths:
  - "app/**/*.ts"
exclude_paths:
  - test/
  - ci/
  - resources/
  - www/
  - typings/
  - lib/*.js
  - dist/*.js
