#
# Configuration
#

sudo: required
dist: trusty

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-22.0.1
    - android-22
  licenses:
    - '.+'

branches:
  only:
    - master

#
# Build Lifecycle:
#

before_install:
  - nvm install 6.0.0
  - nvm use 6.0.0
  - npm install -g cordova ionic
  - npm install -g codeclimate-test-reporter
  - ionic state clear
  - gem install fir-cli

install: npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp build
  - npm test                             # unit tests
  - npm run build                        # ionic build
  # Serve with python as ionic serve needs interaction
  - cd www && python -m SimpleHTTPServer 8100 >> python_serve.log 2>&1 &
  - npm run e2e                          # run e2e tests against ionic

after_failure:
  - cat /home/travis/build/phodal/growth2/python_serve.log
  - cat /home/travis/build/phodal/growth2/ionic_serve.log

after_success:
  # Send coverage info off to cloud ppl
  - codeclimate-test-reporter < coverage/lcov.info

before_deploy:
  - ionic state restore
  - ionic platform add android
  - ionic build android
  - rm -rf www/*.log
  - rm -rf www/build/test
  # `ionic build android` wraps `cordova build android`, which gives a legit exit code if it fails. Ionic does not; test apk exists.
  - ls ./platforms/android/build/outputs/apk/android*.apk

deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true

after_deploy:
  - fir publish ./platforms/android/build/outputs/apk/android-debug.apk -s 'growth-test' -T $API_TOKEN
